### PR TITLE
Add Support samd51

### PR DESCRIPTION
**Pull request by sabas1080**

### CODE REVIEW

**Comment by slyalfa** [comment]
tested on samd51 with example1
I get
Internal Temperature is : 0.00
Internal Temperature is : 0.00
Internal Temperature is : 0.00
Internal Temperature is : 0.00
Internal Temperature is : 0.00
Internal Temperature is : 0.00

**Comment by sabas1080** [comment]
@slyalfa thanks for your test, I will return to this project in a few days

**Comment by qniens** [comment]
I also only get the following print out on a Itsybitsy M4:
`Internal Temperature is : 0.00`

**Comment by sabas1080** [comment]
@slyalfa @qniens I have update this code, do you can test?

**Comment by qniens** [comment]
@sabas1080 Unfortunately I still only get the following print:
`Internal Temperature is : 0.00 `

**Comment by slyalfa** [comment]
still get 
Internal Temperature is : 0.00
Internal Temperature is : 0.00

**Comment by sabas1080** [comment]
@slyalfa @qniens I have fixed activate temperature sensor, do you can test?

**Comment by qniens** [comment]
Hi @sabas1080,
It still only outputs: 
Internal Temperature is : 0.00
Internal Temperature is : 0.00

Sorry...

**Comment by slyalfa** [comment]
unziped https://github.com/ElectronicCats/ElectronicCats_InternalTemperatureZero/archive/addsupportSAMD51.zip

and still get 
Internal Temperature is : 0.00
Internal Temperature is : 0.00

**Comment by slyalfa** [comment]
me too still get 0.00moved ElectronicCats_InternalTemperatureZero-addsupportSAMD51
and unziped https://github.com/ElectronicCats/ElectronicCats_InternalTemperatureZero/archive/addsupportSAMD51.zipin my ~/Arduino/libraries subdir


    On Monday, August 17, 2020, 12:30:44 AM PDT, Quinten Niens <notifications@github.com> wrote:  
 
 


Hi @sabas1080,
It still only outputs:
Internal Temperature is : 0.00
Internal Temperature is : 0.00

Sorry...

**Comment by sabas1080** [comment]
@slyalfa @qniens  I have tested this in my SAMD51, now working :D

**Pull request merged**
