### PR TITLE
Added disable method

### PR DESCRIPTION
**Pull request by amcmahon01**
Added disable() method as a complement to init() as well as a related example. Calling disable() before entering standby saves ~60uA.  Also updated keywords.txt to use tabs instead of spaces as per Arduino Library specification https://arduino.github.io/arduino-cli/library-specification/.

### CODE REVIEW

**Comment by amcmahon01** [comment]
It looks likes checks are failing because the added example uses the RTCZero library.

**Comment by sabas1080** [comment]
Hi @amcmahon01 , excellent work

You must add `required-libraries` to our file of github actions
https://github.com/ElectronicCats/ElectronicCats_InternalTemperatureZero/blob/master/.github/workflows/LibraryBuild.yml

based in the script
https://github.com/ArminJo/arduino-test-compile

and this should work

**Review by sabas1080 — APPROVED** [review]

**Comment by sabas1080** [comment]
@amcmahon01 Thanks! New realease ready

**Comment by amcmahon01** [comment]
Awesome, happy to help!

**Pull request merged**
